language:
- generic
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - texlive-latex-extra
    - texlive-luatex
    - cm-super
    - latexmk
    - tex4ht
    - texlive-fonts-recommended
    - texlive-lang-italian
    - latex-xcolor
    - pgf
    - lmodern
    - aspell
    - aspell-it
script:
- make ci LANG=it
before_deploy:
- git fetch --tags
